<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>WinWhisper</AssemblyName>
    <RootNamespace>WinWhisper</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Runtime.WindowsRuntime">
      <HintPath>$(MSBuildProgramFiles32)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\Facades\System.Runtime.WindowsRuntime.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
